(*-----------------------------------------------------------------------------
The contents of this file are subject to the Mozilla Public License
Version 1.1 (the "License"); you may not use this file except in compliance
with the License. You may obtain a copy of the License at
http://www.mozilla.org/MPL/MPL-1.1.html

Software distributed under the License is distributed on an "AS IS" basis,
WITHOUT WARRANTY OF ANY KIND, either expressed or implied. See the License for
the specific language governing rights and limitations under the License.

The Original Code is: jedivcsdiff.inc

The Initial Developer of the original FreeVCS-Code (FreeVCS) is:
  Thomas Hensle (freevcs@thensle.de)
Code move to JEDI VCS: Thomas Huber (Thomas_D_Huber@t-online.de)

Componentes and used code which is used in this code are explictly stated to
be copyright of the respective author(s).

How to use: This file includes the help context id's used for html help call.
            If you change the jedivcsdiff.hhp (=> jedivcsdiff.chm)
            make sure that you keep the help context id's in sync!
            
Last Modified: see History

Known Issues:
-----------------------------------------------------------------------------

Unit history:

2004/04/12  THuber    - new file created during help change from hlp => chm

*)

const
  IDH_jvcsdiff_welcome = 0;
  IDH_jvcsdiff_syntax_highlighter = 1;
  IDH_jvcsdiff_report_differences = 2;
  IDH_jvcsdiff_options = 3;
  IDH_jvcsdiff_credits_and_copyrights = 4;
  IDH_jvcsdiff_commandline_options = 5;
  IDH_jvcsdiff_editor_properties = 6;
  IDH_jvcsdiff_custom_keywords = 7;

